# Generated by Django 4.1.4 on 2023-01-17 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                (
                    'content_type',
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    'size_kb',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ('s3_bucket', models.CharField(blank=True, max_length=1024, null=True)),
                ('key', models.CharField(blank=True, max_length=1024, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'uploaded_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='uploaded_files',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
