MARKET_LIST = [
    {
        "id": 0.00,
        "isEditable": False,
        "backendName": "Manuelle Eingabe",
        "name": "Manuell angelegt",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 1.00,
        "isEditable": False,
        "backendName": "Mandant (Shop)",
        "name": "Mandant (Shop)",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 2.00,
        "isEditable": False,
        "backendName": "Ebay",
        "name": "Ebay",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 2.01,
        "isEditable": False,
        "backendName": "eBay United States",
        "name": "eBay United States",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 2.02,
        "isEditable": False,
        "backendName": "eBay Canada (English)",
        "name": "eBay Canada (English)",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 2.03,
        "isEditable": False,
        "backendName": "eBay UK",
        "name": "eBay UK",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 2.04,
        "isEditable": False,
        "backendName": "eBay Australia",
        "name": "eBay Australia",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 2.05,
        "isEditable": False,
        "backendName": "eBay Austria",
        "name": "eBay Austria",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 2.06,
        "isEditable": False,
        "backendName": "eBay Belgium (French)",
        "name": "eBay Belgium (French)",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 2.07,
        "isEditable": False,
        "backendName": "eBay France",
        "name": "eBay France",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 2.08,
        "isEditable": False,
        "backendName": "eBay Germany",
        "name": "eBay Germany",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 2.09,
        "isEditable": False,
        "backendName": "eBay Motors",
        "name": "eBay Motors",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 2.10,
        "isEditable": False,
        "backendName": "eBay Italy",
        "name": "eBay Italy",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 2.11,
        "isEditable": False,
        "backendName": "eBay Belgium (Dutch)",
        "name": "eBay Belgium (Dutch)",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 2.12,
        "isEditable": False,
        "backendName": "eBay Netherlands",
        "name": "eBay Netherlands",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 2.13,
        "isEditable": False,
        "backendName": "eBay Spain",
        "name": "eBay Spain",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 2.14,
        "isEditable": False,
        "backendName": "eBay Switzerland",
        "name": "eBay Switzerland",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 2.15,
        "isEditable": False,
        "backendName": "eBay Hong Kong",
        "name": "eBay Hong Kong",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 2.16,
        "isEditable": False,
        "backendName": "eBay India",
        "name": "eBay India",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 2.17,
        "isEditable": False,
        "backendName": "eBay Ireland",
        "name": "eBay Ireland",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 2.18,
        "isEditable": False,
        "backendName": "eBay Malaysia",
        "name": "eBay Malaysia",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 2.19,
        "isEditable": False,
        "backendName": "eBay Canada (French)",
        "name": "eBay Canada (French)",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 2.20,
        "isEditable": False,
        "backendName": "eBay Philippines",
        "name": "eBay Philippines",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 2.21,
        "isEditable": False,
        "backendName": "eBay Poland",
        "name": "eBay Poland",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 2.22,
        "isEditable": False,
        "backendName": "eBay Singapore",
        "name": "eBay Singapore",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 3.00,
        "isEditable": False,
        "backendName": "Elmar",
        "name": "Elmar",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 4.00,
        "isEditable": False,
        "backendName": "Amazon",
        "name": "Amazon",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 4.01,
        "isEditable": False,
        "backendName": "Amazon Germany",
        "name": "Amazon Germany",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 4.02,
        "isEditable": False,
        "backendName": "Amazon UK",
        "name": "Amazon UK",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 4.03,
        "isEditable": False,
        "backendName": "Amazon USA",
        "name": "Amazon USA",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 4.04,
        "isEditable": False,
        "backendName": "Amazon France",
        "name": "Amazon France",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 4.05,
        "isEditable": False,
        "backendName": "Amazon Italy",
        "name": "Amazon Italy",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 4.06,
        "isEditable": False,
        "backendName": "Amazon Spain",
        "name": "Amazon Spain",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 4.07,
        "isEditable": False,
        "backendName": "Amazon Canada",
        "name": "Amazon Canada",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 4.08,
        "isEditable": False,
        "backendName": "Amazon Mexico",
        "name": "Amazon Mexico",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 4.09,
        "isEditable": False,
        "backendName": "Amazon Netherlands",
        "name": "Amazon Netherlands",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 4.11,
        "isEditable": False,
        "backendName": "Amazon Poland",
        "name": "Amazon Poland",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 4.12,
        "isEditable": False,
        "backendName": "Amazon Sweden",
        "name": "Amazon Sweden",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 4.13,
        "isEditable": False,
        "backendName": "Amazon Turkey",
        "name": "Amazon Turkey",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 4.14,
        "isEditable": False,
        "backendName": "Amazon United Arab Emirates (U.A.E.)",
        "name": "Amazon United Arab Emirates (U.A.E.)",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 4.15,
        "isEditable": False,
        "backendName": "Amazon Belgium",
        "name": "Amazon Belgium",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 4.21,
        "isEditable": False,
        "backendName": "Amazon Germany B2B",
        "name": "Amazon Germany B2B",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 4.22,
        "isEditable": False,
        "backendName": "Amazon UK B2B",
        "name": "Amazon UK B2B",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 4.24,
        "isEditable": False,
        "backendName": "Amazon France B2B",
        "name": "Amazon France B2B",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 4.25,
        "isEditable": False,
        "backendName": "Amazon Italy B2B",
        "name": "Amazon Italy B2B",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 4.26,
        "isEditable": False,
        "backendName": "Amazon Spain B2B",
        "name": "Amazon Spain B2B",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 5.00,
        "isEditable": False,
        "backendName": "Yatego",
        "name": "Yatego",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 6.00,
        "isEditable": False,
        "backendName": "Kelkoo",
        "name": "Kelkoo",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 7.00,
        "isEditable": False,
        "backendName": "GoogleProducts",
        "name": "GoogleProducts",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 9.00,
        "isEditable": True,
        "backendName": "backmarket.fr",
        "name": "backmarket.fr",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 10.00,
        "isEditable": True,
        "backendName": "backmarket.be",
        "name": "backmarket.be",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 11.00,
        "isEditable": True,
        "backendName": "backmarket.de",
        "name": "backmarket.de",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 12.00,
        "isEditable": True,
        "backendName": "backmarket.es",
        "name": "backmarket.es",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 13.00,
        "isEditable": True,
        "backendName": "backmarket.it",
        "name": "backmarket.it",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 14.00,
        "isEditable": False,
        "backendName": "EbayFulfillment",
        "name": "eBay Fulfillment by Orange Connex",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "EbayFulfillment",
        "showInLeads": False,
    },
    {
        "id": 15.00,
        "isEditable": True,
        "backendName": "backmarket.at",
        "name": "backmarket.at",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 16.00,
        "isEditable": True,
        "backendName": "backmarket.nl",
        "name": "backmarket.nl",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 17.00,
        "isEditable": True,
        "backendName": "backmarket.co.uk",
        "name": "backmarket.co.uk",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 18.00,
        "isEditable": True,
        "backendName": "backmarket.pt",
        "name": "backmarket.pt",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 19.00,
        "isEditable": True,
        "backendName": "backmarket.fi",
        "name": "backmarket.fi",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 20.00,
        "isEditable": True,
        "backendName": "backmarket.ie",
        "name": "backmarket.ie",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 21.00,
        "isEditable": True,
        "backendName": "backmarket.gr",
        "name": "backmarket.gr",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 22.00,
        "isEditable": False,
        "backendName": "Shopify",
        "name": "Santo Shop",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "Shopify",
        "showInLeads": False,
    },
    {
        "id": 23.00,
        "isEditable": True,
        "backendName": "",
        "name": "refurbed",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 101.00,
        "isEditable": False,
        "backendName": "Ricardo",
        "name": "Ricardo",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 102.00,
        "isEditable": False,
        "backendName": "Kaufland",
        "name": "Kaufland",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 102.01,
        "isEditable": False,
        "backendName": "Kaufland DE",
        "name": "Kaufland DE",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 102.02,
        "isEditable": False,
        "backendName": "Kaufland CZ",
        "name": "Kaufland CZ",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 102.03,
        "isEditable": False,
        "backendName": "Kaufland SK",
        "name": "Kaufland SK",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 103.00,
        "isEditable": False,
        "backendName": "Kassensystem",
        "name": "Kassensystem",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 104.00,
        "isEditable": False,
        "backendName": "Amazon FBA",
        "name": "Amazon FBA",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 104.01,
        "isEditable": False,
        "backendName": "Amazon FBA Germany",
        "name": "Amazon FBA Germany",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 104.02,
        "isEditable": False,
        "backendName": "Amazon FBA UK",
        "name": "Amazon FBA UK",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 104.03,
        "isEditable": False,
        "backendName": "Amazon FBA USA",
        "name": "Amazon FBA USA",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 104.04,
        "isEditable": False,
        "backendName": "Amazon FBA France",
        "name": "Amazon FBA France",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 104.05,
        "isEditable": False,
        "backendName": "Amazon FBA Italy",
        "name": "Amazon FBA Italy",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 104.06,
        "isEditable": False,
        "backendName": "Amazon FBA Spain",
        "name": "Amazon FBA Spain",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 104.07,
        "isEditable": False,
        "backendName": "Amazon FBA Canada",
        "name": "Amazon FBA Canada",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 104.08,
        "isEditable": False,
        "backendName": "Amazon FBA Mexico",
        "name": "Amazon FBA Mexico",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 104.09,
        "isEditable": False,
        "backendName": "Amazon FBA Netherlands",
        "name": "Amazon FBA Netherlands",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 104.11,
        "isEditable": False,
        "backendName": "Amazon FBA Poland",
        "name": "Amazon FBA Poland",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 104.12,
        "isEditable": False,
        "backendName": "Amazon FBA Sweden",
        "name": "Amazon FBA Sweden",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 104.13,
        "isEditable": False,
        "backendName": "Amazon FBA Turkey",
        "name": "Amazon FBA Turkey",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 104.14,
        "isEditable": False,
        "backendName": "Amazon FBA United Arab Emirates (U.A.E.)",
        "name": "Amazon FBA United Arab Emirates (U.A.E.)",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 104.15,
        "isEditable": False,
        "backendName": "Amazon FBA Belgium",
        "name": "Amazon FBA Belgium",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 104.21,
        "isEditable": False,
        "backendName": "Amazon FBA Germany B2B",
        "name": "Amazon FBA Germany B2B",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 104.22,
        "isEditable": False,
        "backendName": "Amazon FBA UK B2B",
        "name": "Amazon FBA UK B2B",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 104.24,
        "isEditable": False,
        "backendName": "Amazon FBA France B2B",
        "name": "Amazon FBA France B2B",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 104.25,
        "isEditable": False,
        "backendName": "Amazon FBA Italy B2B",
        "name": "Amazon FBA Italy B2B",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 104.26,
        "isEditable": False,
        "backendName": "Amazon FBA Spain B2B",
        "name": "Amazon FBA Spain B2B",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 105.00,
        "isEditable": False,
        "backendName": "Zentralverkauf.de",
        "name": "Zentralverkauf.de",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 106.00,
        "isEditable": False,
        "backendName": "Rakuten.de",
        "name": "Rakuten.de",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 107.00,
        "isEditable": False,
        "backendName": "Neckermann.de Enterprise",
        "name": "Neckermann.de Enterprise",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 108.00,
        "isEditable": False,
        "backendName": "Otto Cooperation",
        "name": "Otto Cooperation",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 108.02,
        "isEditable": False,
        "backendName": "Otto Integration",
        "name": "Otto Integration",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 108.03,
        "isEditable": False,
        "backendName": "OTTO Direktversand",
        "name": "OTTO Direktversand",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 108.04,
        "isEditable": False,
        "backendName": "OTTO PreDropshipment",
        "name": "OTTO PreDropshipment",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 109.00,
        "isEditable": False,
        "backendName": "Shopgate",
        "name": "Shopgate",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 112.00,
        "isEditable": False,
        "backendName": "Shopperella",
        "name": "Shopperella",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 115.00,
        "isEditable": False,
        "backendName": "Restposten",
        "name": "Restposten",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 116.00,
        "isEditable": False,
        "backendName": "Kauflux",
        "name": "Kauflux",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 117.00,
        "isEditable": False,
        "backendName": "Home24",
        "name": "Home24",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.00,
        "isEditable": False,
        "backendName": "Zalando",
        "name": "Zalando",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.01,
        "isEditable": False,
        "backendName": "Zalando DE",
        "name": "Zalando DE",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.02,
        "isEditable": False,
        "backendName": "Zalando NL",
        "name": "Zalando NL",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.03,
        "isEditable": False,
        "backendName": "Zalando FR",
        "name": "Zalando FR",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.04,
        "isEditable": False,
        "backendName": "Zalando IT",
        "name": "Zalando IT",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.05,
        "isEditable": False,
        "backendName": "Zalando UK",
        "name": "Zalando UK",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.06,
        "isEditable": False,
        "backendName": "Zalando AT",
        "name": "Zalando AT",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.07,
        "isEditable": False,
        "backendName": "Zalando CH",
        "name": "Zalando CH",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.08,
        "isEditable": False,
        "backendName": "Zalando PL",
        "name": "Zalando PL",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.09,
        "isEditable": False,
        "backendName": "Zalando BE",
        "name": "Zalando BE",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.10,
        "isEditable": False,
        "backendName": "Zalando SE",
        "name": "Zalando SE",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.11,
        "isEditable": False,
        "backendName": "Zalando FI",
        "name": "Zalando FI",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.12,
        "isEditable": False,
        "backendName": "Zalando DK",
        "name": "Zalando DK",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.13,
        "isEditable": False,
        "backendName": "Zalando ES",
        "name": "Zalando ES",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.14,
        "isEditable": False,
        "backendName": "Zalando NO",
        "name": "Zalando NO",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.15,
        "isEditable": False,
        "backendName": "Zalando CZ",
        "name": "Zalando CZ",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.16,
        "isEditable": False,
        "backendName": "Zalando IE",
        "name": "Zalando IE",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.17,
        "isEditable": False,
        "backendName": "Zalando PT",
        "name": "Zalando PT",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.18,
        "isEditable": False,
        "backendName": "Zalando SK",
        "name": "Zalando SK",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.19,
        "isEditable": False,
        "backendName": "Zalando SI",
        "name": "Zalando SI",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.20,
        "isEditable": False,
        "backendName": "Zalando LT",
        "name": "Zalando LT",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.21,
        "isEditable": False,
        "backendName": "Zalando LV",
        "name": "Zalando LV",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.22,
        "isEditable": False,
        "backendName": "Zalando EE",
        "name": "Zalando EE",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.23,
        "isEditable": False,
        "backendName": "Zalando HR",
        "name": "Zalando HR",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.24,
        "isEditable": False,
        "backendName": "Zalando HU",
        "name": "Zalando HU",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 118.25,
        "isEditable": False,
        "backendName": "Zalando RO",
        "name": "Zalando RO",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 119.00,
        "isEditable": False,
        "backendName": "Neckermann.at Enterprise",
        "name": "NeckermannATEP",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 120.00,
        "isEditable": False,
        "backendName": "Neckermann.at Cross-Docking",
        "name": "NeckermannATCD",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 121.00,
        "isEditable": False,
        "backendName": "Idealo",
        "name": "Idealo",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 121.02,
        "isEditable": False,
        "backendName": "idealo Direktkauf",
        "name": "idealo Direktkauf",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 122.00,
        "isEditable": False,
        "backendName": "La Redoute",
        "name": "La Redoute",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 124.00,
        "isEditable": False,
        "backendName": "SumoScout",
        "name": "SumoScout",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 125.00,
        "isEditable": False,
        "backendName": "Hood",
        "name": "Hood",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 127.00,
        "isEditable": False,
        "backendName": "BeezUP",
        "name": "BeezUP",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 130.00,
        "isEditable": False,
        "backendName": "Tracdelight",
        "name": "tracdelight",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 131.00,
        "isEditable": False,
        "backendName": "Plus.de",
        "name": "Plus.de",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 132.00,
        "isEditable": False,
        "backendName": "GartenXXL.de",
        "name": "GartenXXL.de",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 133.00,
        "isEditable": False,
        "backendName": "Twenga",
        "name": "Twenga",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 135.00,
        "isEditable": False,
        "backendName": "Newsletter2Go",
        "name": "Newsletter2GO",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 137.00,
        "isEditable": False,
        "backendName": "Grosshandel.eu",
        "name": "grosshandel.eu",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 138.00,
        "isEditable": False,
        "backendName": "Hertie",
        "name": "0",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 143.00,
        "isEditable": False,
        "backendName": "Cdiscount.com",
        "name": "Cdiscount.com",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 143.02,
        "isEditable": False,
        "backendName": "Cdiscount.com C Logistique",
        "name": "Cdiscount.com C Logistique",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 145.00,
        "isEditable": False,
        "backendName": "Fruugo",
        "name": "Fruugo",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 147.00,
        "isEditable": False,
        "backendName": "Flubit",
        "name": "Flubit",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 148.00,
        "isEditable": False,
        "backendName": "WEB-API",
        "name": "WEB-API",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 149.00,
        "isEditable": False,
        "backendName": "Mercateo",
        "name": "Mercateo",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 150.00,
        "isEditable": False,
        "backendName": "Check24",
        "name": "Check24",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 152.00,
        "isEditable": False,
        "backendName": "bol.com",
        "name": "bol.com",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 152.01,
        "isEditable": False,
        "backendName": "bol.com FBB",
        "name": "bol.com FBB",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 154.00,
        "isEditable": False,
        "backendName": "Netto",
        "name": "Netto",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 156.00,
        "isEditable": False,
        "backendName": "Etsy (not used)",
        "name": "Etsy (not used)",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 160.00,
        "isEditable": False,
        "backendName": "OTTO",
        "name": "OTTO",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 160.10,
        "isEditable": False,
        "backendName": "OTTO market",
        "name": "OTTO market",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 170.00,
        "isEditable": False,
        "backendName": "Kaufland FBK",
        "name": "Kaufland FBK",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 170.01,
        "isEditable": False,
        "backendName": "Kaufland DE FBK",
        "name": "Kaufland DE FBK",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 170.02,
        "isEditable": False,
        "backendName": "Kaufland CZ FBK",
        "name": "Kaufland CZ FBK",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 170.03,
        "isEditable": False,
        "backendName": "Kaufland SK FBK",
        "name": "Kaufland SK FBK",
        "orderOwnerId": "0",
        "isFilterable": True,
        "origin": "plenty",
        "showInLeads": False,
    },
    {
        "id": 171.00,
        "isEditable": False,
        "backendName": "Marktkauf",
        "name": "Marktkauf",
        "orderOwnerId": "0",
        "isFilterable": False,
        "origin": "plenty",
        "showInLeads": False,
    },
]
