# Generated by Django 4.1.4 on 2023-02-23 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_remove_orderticket_delivery_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderedproduct",
            old_name="price",
            new_name="discount",
        ),
        migrations.RenameField(
            model_name="orderedproduct",
            old_name="variant_id",
            new_name="variation_id",
        ),
        migrations.AddField(
            model_name="orderedproduct",
            name="ext_created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 23, 13, 57, 53, 304890)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderedproduct",
            name="ext_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderedproduct",
            name="ext_updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 23, 13, 58, 6, 410110)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderedproduct",
            name="price_gross",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderedproduct",
            name="price_net",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderedproduct",
            name="quantity",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderedproduct",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
