# Generated by Django 4.1.4 on 2023-02-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_rename_price_orderedproduct_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderticket",
            name="invoice_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
