# Generated by Django 4.1.4 on 2023-03-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tickets",
            "0006_rename_invoice_addr_city_orderticket_invoice_addr_extension_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="requestticket",
            name="market",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
