# Generated by Django 4.1.4 on 2023-03-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tickets",
            "0009_rename_invoice_addr_extension_orderticket_invoice_addr_city_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="orderticket",
            name="dhl_return_label_data",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderticket",
            name="dhl_return_shipment_number",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
