# Generated by Django 4.1.4 on 2023-03-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0010_orderticket_dhl_return_label_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderticket",
            name="dhl_shipping_label_number",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="orderticket",
            name="dhl_shipping_label_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
