# Generated by Django 4.1.4 on 2023-03-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0013_orderedproduct_serial_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderticket",
            name="dhl_return_label_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderticket",
            name="dhl_shipping_label_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
